export default {
  name: "title",
  actived: "Estar ativo",
  can_explain_op: "Consegue explicar o assunto",
  study_time: "Estuda o assunto a quanto tempo",
  times_week_necessary_op: "Quantas vezes por semana é necessario",
  domain_week_op: "",
  title: "Título do Evento",
  started_study_op: "Já estuda o assunto",
  lot_to_discuss_op: "É preciso consultar muito material para o evento",
  can_explain_no: "Não",
  can_explain_yes: "Sim",
  theme_id: "Tema do Evento",
  theme:'Tema',
  stage:'Estágio',
  topic:'Topico',
  revision:'Revisão',
  font:'Fonte',
  priority_op_low: "Baixa",
  description:'Em seu dispositivo, ative o digitar por voz e fale sobre o assunto',
};