export enum DataType {
  //int
  tinyint= "number",
  smallint = "number",
  mediumint = "number",
  int = "number",
  bigint = "request",
  decimal = "number",
  float = "number",
  double = "number",
  bi = "number",
  //text
  char = "text",
  varchar = "text",
  binary = "text",
  varbinary = "text",
  tinyblob = "text",
  blob = "text",
  mediumblob = "text",
  longblob = "text",
  tinytext = "text",
  text = "textarea",
  mediumtext = "text",
  longtext = "text",
  enum = "text",
  set = "text",
  //date
  date = "date",
  time = "date",
  datetime = "date",
  timestamp = "date",
  year = "date",
  //spatial
  geometry = "number",
  point = "number",
  linestring = "number",
  polygon = "number",
  geometrycollection = "number",
  multilinestring = "number",
  multipoint = "number",
  multipolygo = "number",
};