let m = require('../utils/ManageData.ts');

describe('ManageData', () => {
    test('o arquivo deve ser um objeto com chave topics', () => {
        let mange =(new m.ManageData(data)).orderByTopic();
        expect(Object.keys(mange)[0]).toBe( "topics");
    })

    test('o arquivo deve ser um objeto com chave stages', () => {
        let mange =(new m.ManageData(data)).orderByStage();
        expect(Object.keys(mange)[0]).toBe( "stages");
    })

    test('o arquivo deve ser um objeto com chave categories', () => {
        let mange =(new m.ManageData(data)).orderByCategory();
        expect(Object.keys(mange)[0]).toBe( "categories");
    })
})


var data = {
    'themes': [
    {   
        "id": 1,
        "name": "Godói e Associados",
        "slug": "consequuntur-at-suscipit-nostrum-porro-et-officia-sed",
        "description": "Eos dolor neque iste officia quas. Amet ut itaque debitis reprehenderit. Velit sed cum voluptas mollitia tempore quo. Ut ipsam omnis autem qui dolorem vel.",
        "created_at": "2026-07-02 10:39:21",
        "updated_at": "2026-07-01 10:51:10",
        "topics": [
            {
                "id": 1,
                "name": "qui",
                "theme_id": 1,
                "slug": "dolor-odit-molestias-saepe-unde-quo-voluptas-illo-rerum",
                "description": "Sint minus provident et tempora. Adipisci maxime dolore veniam reprehenderit aut sint. Non unde delectus eos iusto. Sed aliquam voluptatem nisi non aperiam sunt porro nobis.",
                "created_at": "2026-07-02 10:39:21",
                "updated_at": "2026-07-02 10:39:21",
                "actived": 1,
                "can_explain": null,
                "study_time": null,
                "times_week_necessary": null,
                "domain_week": null,
                "started_study": null,
                "lot_to_discuss": null,
                "end_date": "2026-07-02 10:39:21",
                "stages": [
                    {
                        "id": 1,
                        "name": "Sr. Mário Serra",
                        "topic_id": 1,
                        "slug": "Sr. Mário Serra",
                        "description": null,
                        "created_at": "2026-07-02 10:39:21",
                        "updated_at": "2026-07-02 10:39:21",
                        "summary": null,
                        "synthesis": null,
                        "status": -1,
                        "domain_level": 1,
                        "attention": null,
                        "learning_stage": 4,
                        "priority": 2,
                        "partial_score": 8,
                        "more_advanced": 0
                    },
                    {
                        "id": 2,
                        "name": "Dr. Valentin Lourenço Filho",
                        "topic_id": 1,
                        "slug": "Dr. Valentin Lourenço Filho",
                        "description": null,
                        "created_at": "2026-07-02 10:39:21",
                        "updated_at": "2026-07-02 10:39:21",
                        "summary": null,
                        "synthesis": null,
                        "status": 1,
                        "domain_level": 0,
                        "attention": null,
                        "learning_stage": 2,
                        "priority": 1,
                        "partial_score": 11,
                        "more_advanced": 0
                    },
                    {
                        "id": 3,
                        "name": "Catarina Heloísa Maia",
                        "topic_id": 1,
                        "slug": "Catarina Heloísa Maia",
                        "description": null,
                        "created_at": "2026-07-02 10:39:22",
                        "updated_at": "2026-07-02 10:39:22",
                        "summary": null,
                        "synthesis": null,
                        "status": -1,
                        "domain_level": 1,
                        "attention": null,
                        "learning_stage": 3,
                        "priority": 3,
                        "partial_score": 10,
                        "more_advanced": 0
                    },
                    {
                        "id": 14,
                        "name": "Dr. Pietra Olívia Teles Jr.",
                        "topic_id": 1,
                        "slug": "Dr. Pietra Olívia Teles Jr.",
                        "description": null,
                        "created_at": "2026-07-02 10:39:23",
                        "updated_at": "2026-07-02 10:39:23",
                        "summary": null,
                        "synthesis": null,
                        "status": 1,
                        "domain_level": 0,
                        "attention": null,
                        "learning_stage": 1,
                        "priority": 4,
                        "partial_score": 15,
                        "more_advanced": 0
                    },
                    {
                        "id": 16,
                        "name": "Sra. Adriele Diana Maia Sobrinho",
                        "topic_id": 1,
                        "slug": "Sra. Adriele Diana Maia Sobrinho",
                        "description": null,
                        "created_at": "2026-07-02 10:39:24",
                        "updated_at": "2026-07-02 10:39:24",
                        "summary": null,
                        "synthesis": null,
                        "status": 1,
                        "domain_level": 1,
                        "attention": null,
                        "learning_stage": 2,
                        "priority": 3,
                        "partial_score": 12,
                        "more_advanced": 0
                    },
                    {
                        "id": 28,
                        "name": "Leandro Fidalgo",
                        "topic_id": 1,
                        "slug": "Leandro Fidalgo",
                        "description": null,
                        "created_at": "2026-07-02 10:39:25",
                        "updated_at": "2026-07-02 10:39:25",
                        "summary": null,
                        "synthesis": null,
                        "status": 0,
                        "domain_level": 0,
                        "attention": null,
                        "learning_stage": 3,
                        "priority": 4,
                        "partial_score": 14,
                        "more_advanced": 0
                    },
                    {
                        "id": 37,
                        "name": "Dr. Leonardo Ramos",
                        "topic_id": 1,
                        "slug": "Dr. Leonardo Ramos",
                        "description": null,
                        "created_at": "2026-07-02 10:39:26",
                        "updated_at": "2026-07-02 10:39:26",
                        "summary": null,
                        "synthesis": null,
                        "status": 1,
                        "domain_level": 1,
                        "attention": null,
                        "learning_stage": 4,
                        "priority": 3,
                        "partial_score": 12,
                        "more_advanced": 0
                    }
                ]
            },
            {
                "id": 5,
                "name": "tenetur",
                "theme_id": 1,
                "slug": "quas-facere-magni-nostrum-fugiat-aliquid",
                "description": "Non eum sequi id veniam in quae consectetur. Sed veritatis provident temporibus qui.",
                "created_at": "2026-07-02 10:39:22",
                "updated_at": "2026-07-02 10:39:22",
                "actived": 1,
                "can_explain": null,
                "study_time": null,
                "times_week_necessary": null,
                "domain_week": null,
                "started_study": null,
                "lot_to_discuss": null,
                "end_date": "2026-07-02 10:39:22",
                "stages": [
                    {
                        "id": 12,
                        "name": "Sra. Ana Feliciano Neto",
                        "topic_id": 5,
                        "slug": "Sra. Ana Feliciano Neto",
                        "description": null,
                        "created_at": "2026-07-02 10:39:23",
                        "updated_at": "2026-07-02 10:39:23",
                        "summary": null,
                        "synthesis": null,
                        "status": 1,
                        "domain_level": 1,
                        "attention": null,
                        "learning_stage": 1,
                        "priority": 3,
                        "partial_score": 12,
                        "more_advanced": 0
                    },
                    {
                        "id": 15,
                        "name": "Nero Mauro Torres Jr.",
                        "topic_id": 5,
                        "slug": "Nero Mauro Torres Jr.",
                        "description": null,
                        "created_at": "2026-07-02 10:39:23",
                        "updated_at": "2026-07-02 10:39:23",
                        "summary": null,
                        "synthesis": null,
                        "status": 1,
                        "domain_level": 1,
                        "attention": null,
                        "learning_stage": 2,
                        "priority": 1,
                        "partial_score": 9,
                        "more_advanced": 0
                    },
                    {
                        "id": 22,
                        "name": "Dr. Filipe Quintana Uchoa Jr.",
                        "topic_id": 5,
                        "slug": "Dr. Filipe Quintana Uchoa Jr.",
                        "description": null,
                        "created_at": "2026-07-02 10:39:24",
                        "updated_at": "2026-07-02 10:39:24",
                        "summary": null,
                        "synthesis": null,
                        "status": -1,
                        "domain_level": 0,
                        "attention": null,
                        "learning_stage": 3,
                        "priority": 4,
                        "partial_score": 13,
                        "more_advanced": 0
                    }
                ]
            },
            {
                "id": 6,
                "name": "eligendi",
                "theme_id": 1,
                "slug": "tenetur-delectus-rem-dolore-assumenda-quidem-repellat-soluta",
                "description": "Porro qui laudantium animi fugit est iure ut. Odit corporis veniam eum enim maiores aut nisi. At culpa voluptatum aspernatur et.",
                "created_at": "2026-07-02 10:39:23",
                "updated_at": "2026-07-02 10:39:23",
                "actived": 1,
                "can_explain": null,
                "study_time": null,
                "times_week_necessary": null,
                "domain_week": null,
                "started_study": null,
                "lot_to_discuss": null,
                "end_date": "2026-07-02 10:39:23",
                "stages": [
                    {
                        "id": 20,
                        "name": "Kevin Ferreira Gil",
                        "topic_id": 6,
                        "slug": "Kevin Ferreira Gil",
                        "description": null,
                        "created_at": "2026-07-02 10:39:24",
                        "updated_at": "2026-07-02 10:39:24",
                        "summary": null,
                        "synthesis": null,
                        "status": -1,
                        "domain_level": 1,
                        "attention": null,
                        "learning_stage": 1,
                        "priority": 4,
                        "partial_score": 11,
                        "more_advanced": 0
                    },
                    {
                        "id": 21,
                        "name": "Sr. Marco Ramos Fidalgo",
                        "topic_id": 6,
                        "slug": "Sr. Marco Ramos Fidalgo",
                        "description": null,
                        "created_at": "2026-07-02 10:39:24",
                        "updated_at": "2026-07-02 10:39:24",
                        "summary": null,
                        "synthesis": null,
                        "status": 0,
                        "domain_level": 2,
                        "attention": null,
                        "learning_stage": 2,
                        "priority": 1,
                        "partial_score": 6,
                        "more_advanced": 0
                    },
                    {
                        "id": 40,
                        "name": "Dr. Thomas Ivan Ortiz",
                        "topic_id": 6,
                        "slug": "Dr. Thomas Ivan Ortiz",
                        "description": null,
                        "created_at": "2026-07-02 10:39:27",
                        "updated_at": "2026-07-02 10:39:27",
                        "summary": null,
                        "synthesis": null,
                        "status": 0,
                        "domain_level": 0,
                        "attention": null,
                        "learning_stage": 3,
                        "priority": 4,
                        "partial_score": 14,
                        "more_advanced": 0
                    }
                ]
            }
        ]
    },
    {
        "id": 2,
        "name": "de Aguiar Comercial Ltda.",
        "slug": "inventore-corporis-non-excepturi-maxime-dolor-cum",
        "description": "Quibusdam nulla eaque voluptatem enim voluptate. Adipisci non qui repellendus quia laboriosam ut. Ullam eligendi quam quasi molestiae. Molestias in inventore commodi quo veniam voluptas numquam.",
        "created_at": "2026-07-02 10:39:21",
        "updated_at": "2025-10-23 05:46:55",
        "topics": [
            {
                "id": 2,
                "name": "est",
                "theme_id": 2,
                "slug": "tempore-quisquam-nam-nihil-ullam-facilis",
                "description": "Magnam unde reiciendis asperiores repellat molestiae quas qui commodi. Sit provident ut numquam deleniti omnis. Ducimus voluptas ipsum dolore nostrum ut. Et qui rerum animi quis et asperiores et.",
                "created_at": "2026-07-02 10:39:22",
                "updated_at": "2026-07-02 10:39:22",
                "actived": 1,
                "can_explain": null,
                "study_time": null,
                "times_week_necessary": null,
                "domain_week": null,
                "started_study": null,
                "lot_to_discuss": null,
                "end_date": "2026-07-02 10:39:22",
                "stages": [
                    {
                        "id": 4,
                        "name": "Denis Sales Zamana",
                        "topic_id": 2,
                        "slug": "Denis Sales Zamana",
                        "description": null,
                        "created_at": "2026-07-02 10:39:22",
                        "updated_at": "2026-07-02 10:39:22",
                        "summary": null,
                        "synthesis": null,
                        "status": 0,
                        "domain_level": 2,
                        "attention": null,
                        "learning_stage": 2,
                        "priority": 1,
                        "partial_score": 6,
                        "more_advanced": 0
                    },
                    {
                        "id": 7,
                        "name": "Sr. Alexandre Domingues Jr.",
                        "topic_id": 2,
                        "slug": "Sr. Alexandre Domingues Jr.",
                        "description": null,
                        "created_at": "2026-07-02 10:39:22",
                        "updated_at": "2026-07-02 10:39:22",
                        "summary": null,
                        "synthesis": null,
                        "status": 0,
                        "domain_level": 2,
                        "attention": null,
                        "learning_stage": 2,
                        "priority": 2,
                        "partial_score": 7,
                        "more_advanced": 0
                    },
                    {
                        "id": 8,
                        "name": "Sr. Cristóvão Bezerra Carmona",
                        "topic_id": 2,
                        "slug": "Sr. Cristóvão Bezerra Carmona",
                        "description": null,
                        "created_at": "2026-07-02 10:39:22",
                        "updated_at": "2026-07-02 10:39:22",
                        "summary": null,
                        "synthesis": null,
                        "status": 0,
                        "domain_level": 1,
                        "attention": null,
                        "learning_stage": 4,
                        "priority": 3,
                        "partial_score": 11,
                        "more_advanced": 0
                    },
                    {
                        "id": 27,
                        "name": "Thalissa Jennifer Batista",
                        "topic_id": 2,
                        "slug": "Thalissa Jennifer Batista",
                        "description": null,
                        "created_at": "2026-07-02 10:39:25",
                        "updated_at": "2026-07-02 10:39:25",
                        "summary": null,
                        "synthesis": null,
                        "status": 1,
                        "domain_level": 2,
                        "attention": null,
                        "learning_stage": 4,
                        "priority": 4,
                        "partial_score": 11,
                        "more_advanced": 0
                    }
                ]
            },
            {
                "id": 3,
                "name": "sunt",
                "theme_id": 2,
                "slug": "ea-accusamus-quia-eum-nam",
                "description": "Voluptate reprehenderit excepturi velit quo eius. Rerum laudantium et omnis rem ut reiciendis quam fuga.",
                "created_at": "2026-07-02 10:39:22",
                "updated_at": "2026-07-02 10:39:22",
                "actived": 1,
                "can_explain": null,
                "study_time": null,
                "times_week_necessary": null,
                "domain_week": null,
                "started_study": null,
                "lot_to_discuss": null,
                "end_date": "2026-07-02 10:39:22",
                "stages": [
                    {
                        "id": 5,
                        "name": "Sra. Eloah Giovanna Urias Jr.",
                        "topic_id": 3,
                        "slug": "Sra. Eloah Giovanna Urias Jr.",
                        "description": null,
                        "created_at": "2026-07-02 10:39:22",
                        "updated_at": "2026-07-02 10:39:22",
                        "summary": null,
                        "synthesis": null,
                        "status": -1,
                        "domain_level": 0,
                        "attention": null,
                        "learning_stage": 4,
                        "priority": 2,
                        "partial_score": 10,
                        "more_advanced": 0
                    },
                    {
                        "id": 6,
                        "name": "Samara Colaço Pena Sobrinho",
                        "topic_id": 3,
                        "slug": "Samara Colaço Pena Sobrinho",
                        "description": null,
                        "created_at": "2026-07-02 10:39:22",
                        "updated_at": "2026-07-02 10:39:22",
                        "summary": null,
                        "synthesis": null,
                        "status": 1,
                        "domain_level": 1,
                        "attention": null,
                        "learning_stage": 2,
                        "priority": 3,
                        "partial_score": 12,
                        "more_advanced": 0
                    },
                    {
                        "id": 11,
                        "name": "Fernando Hugo Chaves",
                        "topic_id": 3,
                        "slug": "Fernando Hugo Chaves",
                        "description": null,
                        "created_at": "2026-07-02 10:39:23",
                        "updated_at": "2026-07-02 10:39:23",
                        "summary": null,
                        "synthesis": null,
                        "status": -1,
                        "domain_level": 0,
                        "attention": null,
                        "learning_stage": 2,
                        "priority": 1,
                        "partial_score": 9,
                        "more_advanced": 0
                    },
                    {
                        "id": 13,
                        "name": "Ziraldo Teles Sobrinho",
                        "topic_id": 3,
                        "slug": "Ziraldo Teles Sobrinho",
                        "description": null,
                        "created_at": "2026-07-02 10:39:23",
                        "updated_at": "2026-07-02 10:39:23",
                        "summary": null,
                        "synthesis": null,
                        "status": 1,
                        "domain_level": 0,
                        "attention": null,
                        "learning_stage": 4,
                        "priority": 1,
                        "partial_score": 11,
                        "more_advanced": 0
                    }
                ]
            },
            {
                "id": 15,
                "name": "et",
                "theme_id": 2,
                "slug": "ea-cumque-voluptas-reprehenderit-molestiae-dolor-maiores-suscipit",
                "description": "Sit cum adipisci in est nisi. Soluta rerum est vel atque vero non. Natus excepturi error voluptas illum consequatur tenetur. Minima eos minus est numquam modi ex corrupti.",
                "created_at": "2026-07-02 10:39:25",
                "updated_at": "2026-07-02 10:39:25",
                "actived": 1,
                "can_explain": null,
                "study_time": null,
                "times_week_necessary": null,
                "domain_week": null,
                "started_study": null,
                "lot_to_discuss": null,
                "end_date": "2026-07-02 10:39:25",
                "stages": [
                    {
                        "id": 29,
                        "name": "Srta. Eunice Serra Filho",
                        "topic_id": 15,
                        "slug": "Srta. Eunice Serra Filho",
                        "description": null,
                        "created_at": "2026-07-02 10:39:25",
                        "updated_at": "2026-07-02 10:39:25",
                        "summary": null,
                        "synthesis": null,
                        "status": 1,
                        "domain_level": 2,
                        "attention": null,
                        "learning_stage": 1,
                        "priority": 1,
                        "partial_score": 7,
                        "more_advanced": 0
                    },
                    {
                        "id": 31,
                        "name": "Sr. Gilberto Lourenço Saraiva Filho",
                        "topic_id": 15,
                        "slug": "Sr. Gilberto Lourenço Saraiva Filho",
                        "description": null,
                        "created_at": "2026-07-02 10:39:26",
                        "updated_at": "2026-07-02 10:39:26",
                        "summary": null,
                        "synthesis": null,
                        "status": 1,
                        "domain_level": 2,
                        "attention": null,
                        "learning_stage": 1,
                        "priority": 2,
                        "partial_score": 8,
                        "more_advanced": 0
                    }
                ]
            }
        ]
    },
    {
        "id": 3,
        "name": "Beltrão e Associados",
        "slug": "commodi-eveniet-consequuntur-tempore-voluptatem",
        "description": "Nesciunt quisquam vel ad error aliquid officia id. Minima cumque corporis quis qui voluptatem aut qui nemo. Repellat sint numquam aut perferendis ea amet rerum. Dolorem voluptatem illum dicta eos tempora quos modi a. Eveniet ratione eum molestiae beatae vero velit consequatur.",
        "created_at": "2026-07-02 10:39:22",
        "updated_at": "2026-04-25 07:15:56",
        "topics": [
            {
                "id": 4,
                "name": "pariatur",
                "theme_id": 3,
                "slug": "iusto-voluptas-quia-sint-iusto-rem",
                "description": "Et et sint ut cumque optio minus iusto. Aut asperiores in quia et. Nobis rerum qui ullam doloribus fugiat.",
                "created_at": "2026-07-02 10:39:22",
                "updated_at": "2026-07-02 10:39:22",
                "actived": 1,
                "can_explain": null,
                "study_time": null,
                "times_week_necessary": null,
                "domain_week": null,
                "started_study": null,
                "lot_to_discuss": null,
                "end_date": "2026-07-02 10:39:22",
                "stages": [
                    {
                        "id": 9,
                        "name": "Hugo Carmona Ávila",
                        "topic_id": 4,
                        "slug": "Hugo Carmona Ávila",
                        "description": null,
                        "created_at": "2026-07-02 10:39:22",
                        "updated_at": "2026-07-02 10:39:22",
                        "summary": null,
                        "synthesis": null,
                        "status": 0,
                        "domain_level": 0,
                        "attention": null,
                        "learning_stage": 1,
                        "priority": 4,
                        "partial_score": 14,
                        "more_advanced": 0
                    },
                    {
                        "id": 10,
                        "name": "Flávio Bruno Benez Filho",
                        "topic_id": 4,
                        "slug": "Flávio Bruno Benez Filho",
                        "description": null,
                        "created_at": "2026-07-02 10:39:22",
                        "updated_at": "2026-07-02 10:39:22",
                        "summary": null,
                        "synthesis": null,
                        "status": 1,
                        "domain_level": 2,
                        "attention": null,
                        "learning_stage": 3,
                        "priority": 2,
                        "partial_score": 8,
                        "more_advanced": 0
                    },
                    {
                        "id": 19,
                        "name": "Srta. Michelle Cruz Prado",
                        "topic_id": 4,
                        "slug": "Srta. Michelle Cruz Prado",
                        "description": null,
                        "created_at": "2026-07-02 10:39:24",
                        "updated_at": "2026-07-02 10:39:24",
                        "summary": null,
                        "synthesis": null,
                        "status": 0,
                        "domain_level": 2,
                        "attention": null,
                        "learning_stage": 2,
                        "priority": 1,
                        "partial_score": 6,
                        "more_advanced": 0
                    },
                    {
                        "id": 26,
                        "name": "Fabrício da Cruz Sobrinho",
                        "topic_id": 4,
                        "slug": "Fabrício da Cruz Sobrinho",
                        "description": null,
                        "created_at": "2026-07-02 10:39:25",
                        "updated_at": "2026-07-02 10:39:25",
                        "summary": null,
                        "synthesis": null,
                        "status": 0,
                        "domain_level": 1,
                        "attention": null,
                        "learning_stage": 1,
                        "priority": 1,
                        "partial_score": 8,
                        "more_advanced": 0
                    },
                    {
                        "id": 32,
                        "name": "Isadora Ávila",
                        "topic_id": 4,
                        "slug": "Isadora Ávila",
                        "description": null,
                        "created_at": "2026-07-02 10:39:26",
                        "updated_at": "2026-07-02 10:39:26",
                        "summary": null,
                        "synthesis": null,
                        "status": 1,
                        "domain_level": 0,
                        "attention": null,
                        "learning_stage": 1,
                        "priority": 2,
                        "partial_score": 12,
                        "more_advanced": 0
                    },
                    {
                        "id": 33,
                        "name": "Srta. Mari Stefany Lourenço",
                        "topic_id": 4,
                        "slug": "Srta. Mari Stefany Lourenço",
                        "description": null,
                        "created_at": "2026-07-02 10:39:26",
                        "updated_at": "2026-07-02 10:39:26",
                        "summary": null,
                        "synthesis": null,
                        "status": 0,
                        "domain_level": 2,
                        "attention": null,
                        "learning_stage": 4,
                        "priority": 4,
                        "partial_score": 10,
                        "more_advanced": 0
                    },
                    {
                        "id": 39,
                        "name": "Srta. Juliane Cervantes Pereira Filho",
                        "topic_id": 4,
                        "slug": "Srta. Juliane Cervantes Pereira Filho",
                        "description": null,
                        "created_at": "2026-07-02 10:39:27",
                        "updated_at": "2026-07-02 10:39:27",
                        "summary": null,
                        "synthesis": null,
                        "status": 0,
                        "domain_level": 0,
                        "attention": null,
                        "learning_stage": 1,
                        "priority": 2,
                        "partial_score": 11,
                        "more_advanced": 0
                    }
                ]
            },
            {
                "id": 10,
                "name": "voluptatem",
                "theme_id": 3,
                "slug": "modi-quae-adipisci-et-ut-eius-error-et",
                "description": "Autem ratione et repellendus expedita maiores suscipit. Natus numquam laborum est et. Rerum excepturi sequi asperiores voluptatibus voluptatem quos vitae. Ratione assumenda voluptate dolores in est.",
                "created_at": "2026-07-02 10:39:24",
                "updated_at": "2026-07-02 10:39:24",
                "actived": 1,
                "can_explain": null,
                "study_time": null,
                "times_week_necessary": null,
                "domain_week": null,
                "started_study": null,
                "lot_to_discuss": null,
                "end_date": "2026-07-02 10:39:24",
                "stages": [
                    {
                        "id": 34,
                        "name": "Pâmela Ramires Verdugo",
                        "topic_id": 10,
                        "slug": "Pâmela Ramires Verdugo",
                        "description": null,
                        "created_at": "2026-07-02 10:39:26",
                        "updated_at": "2026-07-02 10:39:26",
                        "summary": null,
                        "synthesis": null,
                        "status": -1,
                        "domain_level": 1,
                        "attention": null,
                        "learning_stage": 4,
                        "priority": 4,
                        "partial_score": 11,
                        "more_advanced": 0
                    }
                ]
            }
        ]
    },
    {
        "id": 4,
        "name": "Pontes e Filhos",
        "slug": "ut-veritatis-libero-laborum-ducimus",
        "description": "Ipsum aut esse expedita. Dignissimos tempora ratione mollitia error. Quia ea vel beatae minima exercitationem. Et corporis minus reprehenderit est esse laborum. Est culpa est magni laborum enim ducimus.",
        "created_at": "2026-07-02 10:39:22",
        "updated_at": "2026-05-22 11:57:41",
        "topics": [
            {
                "id": 7,
                "name": "quod",
                "theme_id": 4,
                "slug": "ut-et-atque-minus-nihil-rerum-in-temporibus",
                "description": "Voluptas ea dolor sequi similique facere modi. Qui vel est nisi est qui. Qui eaque nobis labore minus aut optio ipsam. Maxime voluptatem eum commodi asperiores dolorem mollitia sit.",
                "created_at": "2026-07-02 10:39:23",
                "updated_at": "2026-07-02 10:39:23",
                "actived": 1,
                "can_explain": null,
                "study_time": null,
                "times_week_necessary": null,
                "domain_week": null,
                "started_study": null,
                "lot_to_discuss": null,
                "end_date": "2026-07-02 10:39:23",
                "stages": [
                    {
                        "id": 25,
                        "name": "Juliana Delgado Filho",
                        "topic_id": 7,
                        "slug": "Juliana Delgado Filho",
                        "description": null,
                        "created_at": "2026-07-02 10:39:25",
                        "updated_at": "2026-07-02 10:39:25",
                        "summary": null,
                        "synthesis": null,
                        "status": 0,
                        "domain_level": 1,
                        "attention": null,
                        "learning_stage": 4,
                        "priority": 3,
                        "partial_score": 11,
                        "more_advanced": 0
                    }
                ]
            }
        ]
    },
    {
        "id": 5,
        "name": "Quintana-Rezende",
        "slug": "sed-laboriosam-explicabo-officiis-qui-illum-esse-omnis",
        "description": "Ut omnis itaque et excepturi et aut. Dolore numquam veniam eius aperiam dolorem dignissimos. Aut iste vero ad incidunt consequatur.",
        "created_at": "2026-07-02 10:39:22",
        "updated_at": "2025-12-29 01:20:21",
        "topics": [
            {
                "id": 9,
                "name": "accusamus",
                "theme_id": 5,
                "slug": "qui-non-molestiae-sequi-non",
                "description": "Adipisci quis error perferendis atque delectus dolor. Itaque accusantium corporis exercitationem laboriosam voluptates. Harum voluptatem minima voluptates nostrum qui.",
                "created_at": "2026-07-02 10:39:24",
                "updated_at": "2026-07-02 10:39:24",
                "actived": 1,
                "can_explain": null,
                "study_time": null,
                "times_week_necessary": null,
                "domain_week": null,
                "started_study": null,
                "lot_to_discuss": null,
                "end_date": "2026-07-02 10:39:24",
                "stages": [
                    {
                        "id": 24,
                        "name": "Antonella Paloma Valdez",
                        "topic_id": 9,
                        "slug": "Antonella Paloma Valdez",
                        "description": null,
                        "created_at": "2026-07-02 10:39:25",
                        "updated_at": "2026-07-02 10:39:25",
                        "summary": null,
                        "synthesis": null,
                        "status": 0,
                        "domain_level": 0,
                        "attention": null,
                        "learning_stage": 1,
                        "priority": 1,
                        "partial_score": 10,
                        "more_advanced": 0
                    },
                    {
                        "id": 30,
                        "name": "Srta. Laiane Mia Casanova Sobrinho",
                        "topic_id": 9,
                        "slug": "Srta. Laiane Mia Casanova Sobrinho",
                        "description": null,
                        "created_at": "2026-07-02 10:39:25",
                        "updated_at": "2026-07-02 10:39:25",
                        "summary": null,
                        "synthesis": null,
                        "status": -1,
                        "domain_level": 2,
                        "attention": null,
                        "learning_stage": 3,
                        "priority": 1,
                        "partial_score": 5,
                        "more_advanced": 0
                    },
                    {
                        "id": 38,
                        "name": "Abgail Lívia Lovato Neto",
                        "topic_id": 9,
                        "slug": "Abgail Lívia Lovato Neto",
                        "description": null,
                        "created_at": "2026-07-02 10:39:27",
                        "updated_at": "2026-07-02 10:39:27",
                        "summary": null,
                        "synthesis": null,
                        "status": -1,
                        "domain_level": 1,
                        "attention": null,
                        "learning_stage": 1,
                        "priority": 3,
                        "partial_score": 10,
                        "more_advanced": 0
                    }
                ]
            }
        ]
    },
    {
        "id": 6,
        "name": "Beltrão S.A.",
        "slug": "molestiae-ducimus-dolore-perferendis-rerum-iusto-distinctio-asperiores",
        "description": "Omnis omnis rerum ut. Eum voluptatem eos dolores pariatur magni aut. Id ipsa minus est eaque culpa et.",
        "created_at": "2026-07-02 10:39:22",
        "updated_at": "2026-01-01 12:30:10",
        "topics": [
            {
                "id": 8,
                "name": "tenetur",
                "theme_id": 6,
                "slug": "natus-ut-assumenda-omnis-eveniet",
                "description": "Eum possimus numquam molestias autem. Iusto quos voluptatem porro nobis aut voluptatem et quae. Perferendis laboriosam ex ut velit delectus quia corporis voluptatem.",
                "created_at": "2026-07-02 10:39:23",
                "updated_at": "2026-07-02 10:39:23",
                "actived": 1,
                "can_explain": null,
                "study_time": null,
                "times_week_necessary": null,
                "domain_week": null,
                "started_study": null,
                "lot_to_discuss": null,
                "end_date": "2026-07-02 10:39:23",
                "stages": [
                    {
                        "id": 17,
                        "name": "Dr. Maurício Martines",
                        "topic_id": 8,
                        "slug": "Dr. Maurício Martines",
                        "description": null,
                        "created_at": "2026-07-02 10:39:24",
                        "updated_at": "2026-07-02 10:39:24",
                        "summary": null,
                        "synthesis": null,
                        "status": -1,
                        "domain_level": 0,
                        "attention": null,
                        "learning_stage": 4,
                        "priority": 4,
                        "partial_score": 13,
                        "more_advanced": 0
                    },
                    {
                        "id": 18,
                        "name": "Giovanna Galvão",
                        "topic_id": 8,
                        "slug": "Giovanna Galvão",
                        "description": null,
                        "created_at": "2026-07-02 10:39:24",
                        "updated_at": "2026-07-02 10:39:24",
                        "summary": null,
                        "synthesis": null,
                        "status": 0,
                        "domain_level": 2,
                        "attention": null,
                        "learning_stage": 3,
                        "priority": 4,
                        "partial_score": 10,
                        "more_advanced": 0
                    }
                ]
            },
            {
                "id": 12,
                "name": "tenetur",
                "theme_id": 6,
                "slug": "quidem-perspiciatis-id-sunt-rerum-esse",
                "description": "Rerum nesciunt vel enim velit. Id autem id est nihil. Quas fugiat voluptas quisquam dolor nostrum quis. Sunt fugit laudantium quaerat qui consequatur sequi quod.",
                "created_at": "2026-07-02 10:39:25",
                "updated_at": "2026-07-02 10:39:25",
                "actived": 1,
                "can_explain": null,
                "study_time": null,
                "times_week_necessary": null,
                "domain_week": null,
                "started_study": null,
                "lot_to_discuss": null,
                "end_date": "2026-07-02 10:39:25",
                "stages": [
                    {
                        "id": 23,
                        "name": "Fernanda Sanches Jr.",
                        "topic_id": 12,
                        "slug": "Fernanda Sanches Jr.",
                        "description": null,
                        "created_at": "2026-07-02 10:39:25",
                        "updated_at": "2026-07-02 10:39:25",
                        "summary": null,
                        "synthesis": null,
                        "status": 1,
                        "domain_level": 2,
                        "attention": null,
                        "learning_stage": 1,
                        "priority": 2,
                        "partial_score": 8,
                        "more_advanced": 0
                    },
                    {
                        "id": 35,
                        "name": "Dr. Paulo Renan Uchoa",
                        "topic_id": 12,
                        "slug": "Dr. Paulo Renan Uchoa",
                        "description": null,
                        "created_at": "2026-07-02 10:39:26",
                        "updated_at": "2026-07-02 10:39:26",
                        "summary": null,
                        "synthesis": null,
                        "status": 1,
                        "domain_level": 2,
                        "attention": null,
                        "learning_stage": 1,
                        "priority": 4,
                        "partial_score": 11,
                        "more_advanced": 0
                    }
                ]
            }
        ]
    },
    {
        "id": 12,
        "name": "Carvalho e Filhos",
        "slug": "consectetur-sunt-ipsum-et-optio-ipsa-enim",
        "description": "Id voluptas omnis sequi fuga. Commodi eligendi voluptatum sed sed numquam quam. Rerum quasi hic nostrum dolorum qui quia.",
        "created_at": "2026-07-02 10:39:25",
        "updated_at": "2025-12-25 06:44:45",
        "topics": [
            {
                "id": 18,
                "name": "ratione",
                "theme_id": 12,
                "slug": "delectus-sunt-nobis-tenetur-harum-autem-reiciendis-omnis",
                "description": "Reprehenderit architecto distinctio modi et minus cupiditate consectetur voluptates. Magnam sed veritatis aut iste. Velit est illo cumque error temporibus totam.",
                "created_at": "2026-07-02 10:39:26",
                "updated_at": "2026-07-02 10:39:26",
                "actived": 1,
                "can_explain": null,
                "study_time": null,
                "times_week_necessary": null,
                "domain_week": null,
                "started_study": null,
                "lot_to_discuss": null,
                "end_date": "2026-07-02 10:39:26",
                "stages": [
                    {
                        "id": 36,
                        "name": "Fernando Soares",
                        "topic_id": 18,
                        "slug": "Fernando Soares",
                        "description": null,
                        "created_at": "2026-07-02 10:39:26",
                        "updated_at": "2026-07-02 10:39:26",
                        "summary": null,
                        "synthesis": null,
                        "status": 0,
                        "domain_level": 2,
                        "attention": null,
                        "learning_stage": 2,
                        "priority": 1,
                        "partial_score": 6,
                        "more_advanced": 0
                    }
                ]
            }
        ]
    }
]
}